// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PLI011Sunny</b><br>
 * Generated     : <b>2018/10/27 11:47:09 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  October 27, 2018
 * @author Rodolfo
 */
public abstract class PLI011SunnyHelper extends RationalTestScript
{
	/**
	 * JTextArea: with default state.
	 *		.class : javax.swing.JTextArea
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject DirectionsScreen() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("DirectionsScreen"));
	}
	/**
	 * JTextArea: with specific test context and state.
	 *		.class : javax.swing.JTextArea
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject DirectionsScreen(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("DirectionsScreen"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject ParkingMainDisplay() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("ParkingMainDisplay"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject ParkingMainDisplay(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("ParkingMainDisplay"), anchor, flags);
	}
	
	/**
	 * WelcomeDisplay: with default state.
	 *		.captionText : 
	 * 		.class : client.maindisplay.WelcomeDisplay
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject ParkingMainIDScanner() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("ParkingMainIDScanner"));
	}
	/**
	 * WelcomeDisplay: with specific test context and state.
	 *		.captionText : 
	 * 		.class : client.maindisplay.WelcomeDisplay
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject ParkingMainIDScanner(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("ParkingMainIDScanner"), anchor, flags);
	}
	
	/**
	 * ScanID: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Scan ID
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ParkingMainIDScannerNext() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ParkingMainIDScannerNext"));
	}
	/**
	 * ScanID: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Scan ID
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ParkingMainIDScannerNext(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ParkingMainIDScannerNext"), anchor, flags);
	}
	
	/**
	 * Input: with default state.
	 *		.captionText : Input
	 * 		.class : javax.swing.JDialog
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject ParkingTerminalInput() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("ParkingTerminalInput"));
	}
	/**
	 * Input: with specific test context and state.
	 *		.captionText : Input
	 * 		.class : javax.swing.JDialog
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject ParkingTerminalInput(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("ParkingTerminalInput"), anchor, flags);
	}
	
	/**
	 * Finish: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Finish
	 * 		.classIndex : 1
	 */
	protected GuiTestObject finish() 
	{
		return new GuiTestObject(
                        getMappedTestObject("finish"));
	}
	/**
	 * Finish: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Finish
	 * 		.classIndex : 1
	 */
	protected GuiTestObject finish(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("finish"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject jTextField() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject jTextField(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField"), anchor, flags);
	}
	
	/**
	 * Leave: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Parking Spot #312 
	 * 		accessibleContext.accessibleName : Leave
	 * 		.classIndex : 0
	 */
	protected GuiTestObject leave() 
	{
		return new GuiTestObject(
                        getMappedTestObject("leave"));
	}
	/**
	 * Leave: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Parking Spot #312 
	 * 		accessibleContext.accessibleName : Leave
	 * 		.classIndex : 0
	 */
	protected GuiTestObject leave(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("leave"), anchor, flags);
	}
	
	/**
	 * Next: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Next
	 * 		.classIndex : 1
	 */
	protected GuiTestObject next() 
	{
		return new GuiTestObject(
                        getMappedTestObject("next"));
	}
	/**
	 * Next: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Next
	 * 		.classIndex : 1
	 */
	protected GuiTestObject next(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("next"), anchor, flags);
	}
	
	/**
	 * Next: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Next
	 * 		.classIndex : 1
	 */
	protected GuiTestObject next2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("next2"));
	}
	/**
	 * Next: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Next
	 * 		.classIndex : 1
	 */
	protected GuiTestObject next2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("next2"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : OK
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : OK
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"), anchor, flags);
	}
	
	/**
	 * ParkingNotification: with default state.
	 *		.captionText : 
	 * 		.class : client.maindisplay.ParkingNotification
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject parkingNotification() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("parkingNotification"));
	}
	/**
	 * ParkingNotification: with specific test context and state.
	 *		.captionText : 
	 * 		.class : client.maindisplay.ParkingNotification
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject parkingNotification(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("parkingNotification"), anchor, flags);
	}
	
	/**
	 * PleaseEnterTheParkingSpotNumberOfTheDisplay: with default state.
	 *		.class : javax.swing.plaf.basic.BasicOptionPaneUI$MultiplexingTextField
	 * 		.priorLabel : Please enter the parking spot number of the display
	 * 		name : OptionPane.textField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject pleaseEnterTheParkingSpotNumbe() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("pleaseEnterTheParkingSpotNumbe"));
	}
	/**
	 * PleaseEnterTheParkingSpotNumberOfTheDisplay: with specific test context and state.
	 *		.class : javax.swing.plaf.basic.BasicOptionPaneUI$MultiplexingTextField
	 * 		.priorLabel : Please enter the parking spot number of the display
	 * 		name : OptionPane.textField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject pleaseEnterTheParkingSpotNumbe(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("pleaseEnterTheParkingSpotNumbe"), anchor, flags);
	}
	
	/**
	 * ScanID: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Parking Spot Status: Reserved
	 * 		accessibleContext.accessibleName : Scan ID
	 * 		.classIndex : 0
	 */
	protected GuiTestObject scanID() 
	{
		return new GuiTestObject(
                        getMappedTestObject("scanID"));
	}
	/**
	 * ScanID: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Parking Spot Status: Reserved
	 * 		accessibleContext.accessibleName : Scan ID
	 * 		.classIndex : 0
	 */
	protected GuiTestObject scanID(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("scanID"), anchor, flags);
	}
	
	/**
	 * SecurityDisplayFrame: with default state.
	 *		.captionText : 
	 * 		.class : client.security.SecurityDisplayFrame
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject securityDisplayFrame() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("securityDisplayFrame"));
	}
	/**
	 * SecurityDisplayFrame: with specific test context and state.
	 *		.captionText : 
	 * 		.class : client.security.SecurityDisplayFrame
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject securityDisplayFrame(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("securityDisplayFrame"), anchor, flags);
	}
	
	/**
	 * SpotDisplayFrame: with default state.
	 *		.captionText : 
	 * 		.class : client.parkingdisplay.SpotDisplayFrame
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject spotDisplayFrame() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("spotDisplayFrame"));
	}
	/**
	 * SpotDisplayFrame: with specific test context and state.
	 *		.captionText : 
	 * 		.class : client.parkingdisplay.SpotDisplayFrame
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject spotDisplayFrame(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("spotDisplayFrame"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point MichelleSolanoDirections object in the SUT.
	 */
	protected IFtVerificationPoint MichelleSolanoDirectionsVP() 
	{
		return vp("MichelleSolanoDirections");
	}
	protected IFtVerificationPoint MichelleSolanoDirectionsVP(TestObject anchor)
	{
		return vp("MichelleSolanoDirections", anchor);
	}
	
	/**
	 * Locate and return the verification point NickCaceresDirections object in the SUT.
	 */
	protected IFtVerificationPoint NickCaceresDirectionsVP() 
	{
		return vp("NickCaceresDirections");
	}
	protected IFtVerificationPoint NickCaceresDirectionsVP(TestObject anchor)
	{
		return vp("NickCaceresDirections", anchor);
	}
	
	/**
	 * Locate and return the verification point userDirections object in the SUT.
	 */
	protected IFtVerificationPoint userDirectionsVP() 
	{
		return vp("userDirections");
	}
	protected IFtVerificationPoint userDirectionsVP(TestObject anchor)
	{
		return vp("userDirections", anchor);
	}
	
	

	protected PLI011SunnyHelper()
	{
		setScriptName("PLI011Sunny");
	}
	
}

