// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PLIS05</b><br>
 * Generated     : <b>2018/10/12 10:01:24 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  October 12, 2018
 * @author RexAevum
 */
public abstract class PLIS05Helper extends RationalTestScript
{
	/**
	 * Cancel: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Press next to notify the security officer
	 * 		accessibleContext.accessibleName : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject cancel() 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancel"));
	}
	/**
	 * Cancel: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Press next to notify the security officer
	 * 		accessibleContext.accessibleName : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject cancel(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancel"), anchor, flags);
	}
	
	/**
	 * DuplicateIDNotification: with default state.
	 *		.captionText : Duplicate ID Notification
	 * 		.class : javax.swing.JDialog
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject duplicateIDNotification() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("duplicateIDNotification"));
	}
	/**
	 * DuplicateIDNotification: with specific test context and state.
	 *		.captionText : Duplicate ID Notification
	 * 		.class : javax.swing.JDialog
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject duplicateIDNotification(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("duplicateIDNotification"), anchor, flags);
	}
	
	/**
	 * Finish: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Finish
	 * 		.classIndex : 1
	 */
	protected GuiTestObject finish() 
	{
		return new GuiTestObject(
                        getMappedTestObject("finish"));
	}
	/**
	 * Finish: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Finish
	 * 		.classIndex : 1
	 */
	protected GuiTestObject finish(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("finish"), anchor, flags);
	}
	
	/**
	 * Input: with default state.
	 *		.captionText : Input
	 * 		.class : javax.swing.JDialog
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject input() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("input"));
	}
	/**
	 * Input: with specific test context and state.
	 *		.captionText : Input
	 * 		.class : javax.swing.JDialog
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject input(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("input"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject jTextField() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject jTextField(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject jTextField2() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField2"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject jTextField2(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField2"), anchor, flags);
	}
	
	/**
	 * Leave: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Parking Spot #315 
	 * 		accessibleContext.accessibleName : Leave
	 * 		.classIndex : 0
	 */
	protected GuiTestObject leave() 
	{
		return new GuiTestObject(
                        getMappedTestObject("leave"));
	}
	/**
	 * Leave: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Parking Spot #315 
	 * 		accessibleContext.accessibleName : Leave
	 * 		.classIndex : 0
	 */
	protected GuiTestObject leave(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("leave"), anchor, flags);
	}
	
	/**
	 * Next: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Next
	 * 		.classIndex : 1
	 */
	protected GuiTestObject next() 
	{
		return new GuiTestObject(
                        getMappedTestObject("next"));
	}
	/**
	 * Next: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Next
	 * 		.classIndex : 1
	 */
	protected GuiTestObject next(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("next"), anchor, flags);
	}
	
	/**
	 * Next: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Next
	 * 		.classIndex : 1
	 */
	protected GuiTestObject next2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("next2"));
	}
	/**
	 * Next: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Next
	 * 		.classIndex : 1
	 */
	protected GuiTestObject next2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("next2"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : OK
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : OK
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : OK
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok2"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : OK
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok2"), anchor, flags);
	}
	
	/**
	 * ParkingNotification: with default state.
	 *		.captionText : 
	 * 		.class : client.maindisplay.ParkingNotification
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject parkingNotification() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("parkingNotification"));
	}
	/**
	 * ParkingNotification: with specific test context and state.
	 *		.captionText : 
	 * 		.class : client.maindisplay.ParkingNotification
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject parkingNotification(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("parkingNotification"), anchor, flags);
	}
	
	/**
	 * PleaseEnterTheParkingSpotNumberOfTheDisplay: with default state.
	 *		.class : javax.swing.plaf.basic.BasicOptionPaneUI$MultiplexingTextField
	 * 		.priorLabel : Please enter the parking spot number of the display
	 * 		name : OptionPane.textField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject pleaseEnterTheParkingSpotNumbe() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("pleaseEnterTheParkingSpotNumbe"));
	}
	/**
	 * PleaseEnterTheParkingSpotNumberOfTheDisplay: with specific test context and state.
	 *		.class : javax.swing.plaf.basic.BasicOptionPaneUI$MultiplexingTextField
	 * 		.priorLabel : Please enter the parking spot number of the display
	 * 		name : OptionPane.textField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject pleaseEnterTheParkingSpotNumbe(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("pleaseEnterTheParkingSpotNumbe"), anchor, flags);
	}
	
	/**
	 * ScanID: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Scan ID
	 * 		.classIndex : 0
	 */
	protected GuiTestObject scanID() 
	{
		return new GuiTestObject(
                        getMappedTestObject("scanID"));
	}
	/**
	 * ScanID: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Scan ID
	 * 		.classIndex : 0
	 */
	protected GuiTestObject scanID(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("scanID"), anchor, flags);
	}
	
	/**
	 * ScanID: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Parking Spot Status: Reserved
	 * 		accessibleContext.accessibleName : Scan ID
	 * 		.classIndex : 0
	 */
	protected GuiTestObject scanID2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("scanID2"));
	}
	/**
	 * ScanID: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Parking Spot Status: Reserved
	 * 		accessibleContext.accessibleName : Scan ID
	 * 		.classIndex : 0
	 */
	protected GuiTestObject scanID2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("scanID2"), anchor, flags);
	}
	
	/**
	 * SecurityDisplayFrame: with default state.
	 *		.captionText : 
	 * 		.class : client.security.SecurityDisplayFrame
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject securityDisplayFrame() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("securityDisplayFrame"));
	}
	/**
	 * SecurityDisplayFrame: with specific test context and state.
	 *		.captionText : 
	 * 		.class : client.security.SecurityDisplayFrame
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject securityDisplayFrame(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("securityDisplayFrame"), anchor, flags);
	}
	
	/**
	 * SpotDisplayFrame: with default state.
	 *		.captionText : 
	 * 		.class : client.parkingdisplay.SpotDisplayFrame
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject spotDisplayFrame() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("spotDisplayFrame"));
	}
	/**
	 * SpotDisplayFrame: with specific test context and state.
	 *		.captionText : 
	 * 		.class : client.parkingdisplay.SpotDisplayFrame
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject spotDisplayFrame(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("spotDisplayFrame"), anchor, flags);
	}
	
	/**
	 * WelcomeDisplay: with default state.
	 *		.captionText : 
	 * 		.class : client.maindisplay.WelcomeDisplay
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject welcomeDisplay() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("welcomeDisplay"));
	}
	/**
	 * WelcomeDisplay: with specific test context and state.
	 *		.captionText : 
	 * 		.class : client.maindisplay.WelcomeDisplay
	 * 		accessibleContext.accessibleName : 
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject welcomeDisplay(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("welcomeDisplay"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point duplicateID object in the SUT.
	 */
	protected IFtVerificationPoint duplicateIDVP() 
	{
		return vp("duplicateID");
	}
	protected IFtVerificationPoint duplicateIDVP(TestObject anchor)
	{
		return vp("duplicateID", anchor);
	}
	
	/**
	 * Locate and return the verification point securityCall object in the SUT.
	 */
	protected IFtVerificationPoint securityCallVP() 
	{
		return vp("securityCall");
	}
	protected IFtVerificationPoint securityCallVP(TestObject anchor)
	{
		return vp("securityCall", anchor);
	}
	
	/**
	 * Locate and return the verification point securityNotCall object in the SUT.
	 */
	protected IFtVerificationPoint securityNotCallVP() 
	{
		return vp("securityNotCall");
	}
	protected IFtVerificationPoint securityNotCallVP(TestObject anchor)
	{
		return vp("securityNotCall", anchor);
	}
	
	

	protected PLIS05Helper()
	{
		setScriptName("PLIS05");
	}
	
}

