// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Script2</b><br>
 * Generated     : <b>2018/10/14 11:02:17 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  October 14, 2018
 * @author noiseyRandomness
 */
public abstract class Script2Helper extends RationalTestScript
{
	/**
	 * Input: with default state.
	 *		.text : Input
	 * 		.class : SunAwtDialog
	 * 		.processName : java.exe
	 * 		.name : Input
	 */
	protected TopLevelSubitemTestObject inputwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("inputwindow"));
	}
	/**
	 * Input: with specific test context and state.
	 *		.text : Input
	 * 		.class : SunAwtDialog
	 * 		.processName : java.exe
	 * 		.name : Input
	 */
	protected TopLevelSubitemTestObject inputwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("inputwindow"), anchor, flags);
	}
	
	/**
	 * SunAwtFrame: with default state.
	 *		.text : null
	 * 		.class : SunAwtFrame
	 * 		.processName : java.exe
	 * 		.name : null
	 */
	protected TopLevelSubitemTestObject sunAwtFramewindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sunAwtFramewindow"));
	}
	/**
	 * SunAwtFrame: with specific test context and state.
	 *		.text : null
	 * 		.class : SunAwtFrame
	 * 		.processName : java.exe
	 * 		.name : null
	 */
	protected TopLevelSubitemTestObject sunAwtFramewindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sunAwtFramewindow"), anchor, flags);
	}
	
	

	protected Script2Helper()
	{
		setScriptName("Script2");
	}
	
}

